#!/usr/bin/env zsh

pushd $DOTFILES

os_name="$(uname -s)"

for folder in */; do
  if [[ "$os_name" == "Linux" && "$folder" == "mac/" ]]; then
    continue
  fi

  if [[ "$os_name" == "Darwin" && "$folder" == "linux/" ]]; then
    continue
  fi
    
  echo "stow $folder"
  stow --restow "${folder%/}"
done
popd
