#!/usr/bin/env bash

# Start a new tmux session if none are active
if ! tmux list-sessions &>/dev/null; then
    tmux new-session -ds temp_session
    tmux detach -s temp_session
fi

# Check if a directory was provided as an argument
if [[ $# -eq 1 ]]; then
    dir_selected=$1
    dir_selected_name=$(basename "$dir_selected" | tr . _)

    if tmux has-session -t "$dir_selected_name" 2>/dev/null; then
        # If a session exists, attach to it
        if [[ -n "$TMUX" ]]; then
            tmux switch-client -t "$dir_selected_name"
        else
            tmux attach-session -t "$dir_selected_name"
        fi
    else
        # Create a new session and attach
        tmux new-session -ds "$dir_selected_name" -c "$dir_selected"
        if [[ -n "$TMUX" ]]; then
            tmux switch-client -t "$dir_selected_name"
        else
            tmux attach-session -t "$dir_selected_name"
        fi
        fi
        exit 0

    else
        dir_selected=$(find ~/Development ~/.config ~/.dotfiles -mindepth 0 -maxdepth 2 -type d | fzf)
    fi

    if [[ -z $dir_selected ]]; then
        exit 0
    fi

    dir_selected_name=$(basename "$dir_selected" | tr . _)

    tmux new-session -ds "$dir_selected_name" -c "$dir_selected"
    if [[ -n "$TMUX" ]]; then
        tmux switch-client -t "$dir_selected_name"
    else
        tmux attach-session -t "$dir_selected_name"
    fi
