require("config.autocmds")
require("config.globals")
require("config.keymaps")
require("config.options")
require("config.lsp")

require("plugins.colorscheme")
require("plugins.conform")
require("plugins.copilot")
require("plugins.mini")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.vim-tmux-navigator")
