[tools]
ast-grep = "latest"
biome = "latest"
dprint = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
lua-language-server = "latest"
node = "latest"
"npm:prettier" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:typescript-svelte-plugin" = "latest"
"npm:yaml-language-server" = "latest"
shfmt = "latest"
stylua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
