[tools]
dprint = "latest"
lua-language-server = "latest"
node = "latest"
"npm:prettier" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@typescript/native-preview" = "latest"
stylua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
